export const products = [
  {
    id: 1,
    name: 'Smartphone',
    category: 'Electronics',
    price: 699.99,
    description:
      'High-end smartphone with a 6.5-inch display, 128GB storage, and a 12MP camera.',
    stock: 50,
    manufacturer: 'TechBrand',
    sku: 'TB-SMART-001',
  },
  {
    id: 2,
    name: 'Laptop',
    category: 'Electronics',
    price: 999.99,
    description:
      'Powerful laptop with a 15.6-inch display, 256GB SSD, 8GB RAM, and Intel i7 processor.',
    stock: 30,
    manufacturer: 'CompTech',
    sku: 'CT-LAPTOP-002',
  },
  {
    id: 3,
    name: 'Headphones',
    category: 'Accessories',
    price: 199.99,
    description:
      'Wireless over-ear headphones with noise cancellation and 20-hour battery life.',
    stock: 100,
    manufacturer: 'SoundMax',
    sku: 'SM-HEAD-003',
  },
  {
    id: 4,
    name: 'Smartwatch',
    category: 'Wearables',
    price: 299.99,
    description:
      'Fitness smartwatch with heart rate monitor, GPS, and a 1.4-inch display.',
    stock: 75,
    manufacturer: 'FitTech',
    sku: 'FT-WATCH-004',
  },
  {
    id: 5,
    name: 'Bluetooth Speaker',
    category: 'Audio',
    price: 149.99,
    description:
      'Portable Bluetooth speaker with 360-degree sound and 12-hour battery life.',
    stock: 120,
    manufacturer: 'AudioWave',
    sku: 'AW-SPEAK-005',
  },
  {
    id: 6,
    name: 'Tablet',
    category: 'Electronics',
    price: 499.99,
    description:
      '10-inch tablet with 64GB storage, 8MP camera, and WiFi connectivity.',
    stock: 40,
    manufacturer: 'GadgetPro',
    sku: 'GP-TABLET-006',
  },
  {
    id: 7,
    name: 'Gaming Console',
    category: 'Electronics',
    price: 399.99,
    description:
      'Next-gen gaming console with 1TB storage and 4K resolution support.',
    stock: 20,
    manufacturer: 'GameMaster',
    sku: 'GM-CONSOLE-007',
  },
  {
    id: 8,
    name: 'Wireless Mouse',
    category: 'Accessories',
    price: 49.99,
    description:
      'Ergonomic wireless mouse with adjustable DPI and long battery life.',
    stock: 150,
    manufacturer: 'ClickGear',
    sku: 'CG-MOUSE-008',
  },
  {
    id: 9,
    name: 'Keyboard',
    category: 'Accessories',
    price: 79.99,
    description:
      'Mechanical keyboard with RGB backlighting and customizable keys.',
    stock: 60,
    manufacturer: 'TypeTech',
    sku: 'TT-KEYBOARD-009',
  },
  {
    id: 10,
    name: 'Smart Thermostat',
    category: 'Home Automation',
    price: 129.99,
    description:
      'Smart thermostat with remote control and energy-saving features.',
    stock: 80,
    manufacturer: 'HomeSmart',
    sku: 'HS-THERMO-010',
  },
  {
    id: 11,
    name: 'Fitness Tracker',
    category: 'Wearables',
    price: 79.99,
    description:
      'Fitness tracker with heart rate monitor, step counter, and sleep tracking.',
    stock: 200,
    manufacturer: 'FitTrack',
    sku: 'FT-TRACK-011',
  },
  {
    id: 12,
    name: '4K TV',
    category: 'Electronics',
    price: 799.99,
    description: '55-inch 4K Ultra HD TV with HDR and smart features.',
    stock: 25,
    manufacturer: 'ViewMaster',
    sku: 'VM-TV-012',
  },
  {
    id: 13,
    name: 'Electric Toothbrush',
    category: 'Personal Care',
    price: 59.99,
    description:
      'Electric toothbrush with multiple brushing modes and a rechargeable battery.',
    stock: 90,
    manufacturer: 'SmileBright',
    sku: 'SB-TOOTH-013',
  },
  {
    id: 14,
    name: 'Air Purifier',
    category: 'Home Appliances',
    price: 199.99,
    description:
      'HEPA air purifier with multiple fan speeds and a timer function.',
    stock: 70,
    manufacturer: 'PureAir',
    sku: 'PA-PURIFIER-014',
  },
  {
    id: 15,
    name: 'Coffee Maker',
    category: 'Kitchen Appliances',
    price: 99.99,
    description:
      'Programmable coffee maker with a 12-cup capacity and brew strength control.',
    stock: 60,
    manufacturer: 'BrewMaster',
    sku: 'BM-COFFEE-015',
  },
  {
    id: 16,
    name: 'Smart Light Bulb',
    category: 'Home Automation',
    price: 19.99,
    description:
      'Smart LED light bulb with color changing and remote control features.',
    stock: 500,
    manufacturer: 'BrightLife',
    sku: 'BL-LIGHT-016',
  },
  {
    id: 17,
    name: 'Security Camera',
    category: 'Home Security',
    price: 149.99,
    description:
      'Wireless security camera with night vision and motion detection.',
    stock: 40,
    manufacturer: 'SecureHome',
    sku: 'SH-CAMERA-017',
  },
  {
    id: 18,
    name: 'Electric Kettle',
    category: 'Kitchen Appliances',
    price: 39.99,
    description: 'Electric kettle with rapid boil and auto shut-off features.',
    stock: 100,
    manufacturer: 'QuickBoil',
    sku: 'QB-KETTLE-018',
  },
  {
    id: 19,
    name: 'Robotic Vacuum',
    category: 'Home Appliances',
    price: 299.99,
    description:
      'Robotic vacuum cleaner with smart navigation and multiple cleaning modes.',
    stock: 45,
    manufacturer: 'CleanBot',
    sku: 'CB-VACUUM-019',
  },
  {
    id: 20,
    name: 'Wireless Charger',
    category: 'Accessories',
    price: 29.99,
    description:
      'Fast wireless charger compatible with a variety of smartphones.',
    stock: 200,
    manufacturer: 'ChargePro',
    sku: 'CP-CHARGER-020',
  },
];
